DEFINE VARIABLE iCont AS INTEGER     NO-UNDO.

OUTPUT TO "c:\temp\esco007.csv".

PUT "cod-estabel;"
    "cod-rep;"
    "dt-apuracao;"
    "dt-digita;"
    "dt-integracao;"
    "dt-today;"
    "dt-trans;"
    "dt-vencto;"
    "ep-codigo;"
    "esp-docto;"
    "integrado;"
    "nro-docto;"
    "nro-docto-ap;"
    "Observacao;"
    "origem;"
    "parcela;"
    "referencia;"
    "serie;"
    "tp-movto;"
    "u-char-1;"
    "u-char-2;"
    "u-date-1;"
    "u-date-2;"
    "u-dec-1;"
    "u-dec-2;"
    "u-int-1;"
    "u-int-2;"
    "usuario;"
    "valor" SKIP.

FOR EACH es-movto-comis WHERE es-movto-comis.origem = "MANUAL" NO-LOCK:

    PUT es-movto-comis.cod-estabel      ";"
        es-movto-comis.cod-rep          ";"
        es-movto-comis.dt-apuracao      ";"
        es-movto-comis.dt-digita        ";"
        es-movto-comis.dt-integracao    ";"
        es-movto-comis.dt-today         ";"
        es-movto-comis.dt-trans         ";"
        es-movto-comis.dt-vencto        ";"
        es-movto-comis.ep-codigo        ";"
        es-movto-comis.esp-docto        ";"
        es-movto-comis.integrado        ";"
        es-movto-comis.nro-docto        ";"
        es-movto-comis.nro-docto-ap     ";"
        es-movto-comis.Observacao       ";"
        es-movto-comis.origem           ";"
        es-movto-comis.parcela          ";"
        es-movto-comis.referencia       ";"
        es-movto-comis.serie            ";"
        es-movto-comis.tp-movto         ";"
        es-movto-comis.u-char-1         ";"
        es-movto-comis.u-char-2         ";"
        es-movto-comis.u-date-1         ";"
        es-movto-comis.u-date-2         ";"
        es-movto-comis.u-dec-1          ";"
        es-movto-comis.u-dec-2          ";"
        es-movto-comis.u-int-1          ";"
        es-movto-comis.u-int-2          ";"
        es-movto-comis.usuario          ";"
        es-movto-comis.valor           SKIP.
END.
OUTPUT CLOSE.
