DEFINE VARIABLE cTermo AS CHARACTER   NO-UNDO.
DEFINE VARIABLE iCont AS INTEGER     NO-UNDO.
ASSIGN cTermo = "700,701,702".

DO iCont = 1 TO NUM-ENTRIES(cTermo,","):
    MESSAGE ENTRY(iCont,cTermo,",")
            VIEW-AS ALERT-BOX INFO BUTTONS OK.
END.
